// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8m8vABNvewFTXcozIXYtP4ak1E7vKDE',
    appId: '1:196742219163:web:d3b67cfecf0b6e4cc00d3e',
    messagingSenderId: '196742219163',
    projectId: 'goubi-360003',
    authDomain: 'goubi-360003.firebaseapp.com',
    databaseURL: 'https://goubi-360003-default-rtdb.firebaseio.com',
    storageBucket: 'goubi-360003.appspot.com',
    measurementId: 'G-6JD26YNK0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2KcESfKBlGdl60vPRy0HvtWmtRYInXb8',
    appId: '1:196742219163:android:d963acfeeb5597cac00d3e',
    messagingSenderId: '196742219163',
    projectId: 'goubi-360003',
    databaseURL: 'https://goubi-360003-default-rtdb.firebaseio.com',
    storageBucket: 'goubi-360003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Gu3YB0kxz1js1CnV-VsA-b9bjorR99Y',
    appId: '1:196742219163:ios:3ac0200eaacc56cfc00d3e',
    messagingSenderId: '196742219163',
    projectId: 'goubi-360003',
    databaseURL: 'https://goubi-360003-default-rtdb.firebaseio.com',
    storageBucket: 'goubi-360003.appspot.com',
    iosClientId: '196742219163-h5pudqurumkadpvc3gr2vulikg40sf9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.goubiDelivery',
  );
}
